version: '3.3'

services:
  db:
    image: postgres:15-alpine
    container_name: securenotes-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: securenotes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: securenotes-backend
    restart: unless-stopped
    ports:
      - "8080:8080" # Keep backend on 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/securenotes_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: securenotes-frontend
    restart: unless-stopped
    ports:
      - "80:80" # Map host port 80 to container port 80
    depends_on:
      - backend

volumes:
  postgres-data:
